### ISSUE TITLE
Generate verilog through CIRCT/firtool

### ISSUE THREAD

**Issue by wangliwei-intel** [ucb-bar/chipyard#1162] opened 2022-04-27 12:37 UTC
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Feature Description

CIRCT/firtool is quite mature now, is it possible to generate verilog through it?

B. R.
Liwei

### Motivating Example

To my experiments, it has better verilog emission in terms of readability, less resource utilization.

**Comment by jerryz123** [comment] 2022-09-02 01:24
Duplicate of #1189

**Closed by jerryz123** 2022-09-02 01:24 UTC
Labels: enhancement
